[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
raydium_cp_swap = "PkNZ3YjzrtxV16wdfcZPVKaA71dp3kAdhyHb72L2X4k"


[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

